# Generated by Django 4.2.3 on 2023-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Колір взуття')),
            ],
        ),
        migrations.CreateModel(
            name='SizeShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Розмір взуття')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=32, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Опис взуття')),
                ('price_opt', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ціна ОПТ')),
                ('price_outlet', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ціна РОЗ')),
                ('image', models.ImageField(upload_to='shoes_images', verbose_name='Фото')),
                ('quantity', models.ManyToManyField(to='bot.colorshoes', verbose_name='Наявність взуття')),
            ],
        ),
        migrations.AddField(
            model_name='colorshoes',
            name='quantity',
            field=models.ManyToManyField(to='bot.sizeshoes'),
        ),
    ]
